name: Deploy to Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Iosevka NF font
        run: |
          # Create fonts directory
          mkdir -p ~/.local/share/fonts

          # Download Iosevka NF font (adjust version as needed)
          wget -O iosevka-nf.zip "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Iosevka.zip"

          # Extract and install fonts
          unzip iosevka-nf.zip -d ~/.local/share/fonts/

          # Update font cache
          fc-cache -fv

          # Verify font installation
          fc-list | grep -i iosevka || echo "Iosevka font not found in cache"

      - name: Install Typst
        run: |
          curl -fsSL https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJ
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          typst --version

      - name: Build docs
        run: make

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
